version: '3.5'

services:
  postgres:
    container_name: setupshowroom-postgres
    hostname: setupshowroom-postgres
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_DB=setupshowroom
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5432:5432"
    networks:
      - setupshowroom

  minio:
    container_name: setupshowroom-minio
    hostname: setupshowroom-minio
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    ports:
      - "9090:9000"
      - "9091:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - setupshowroom

  minio-mc:
    container_name: setupshowroom-minio-mc
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/bash -c "
      sleep 3 &&
      /usr/bin/mc alias set localminio http://setupshowroom-minio:9000 admin admin123 &&
      /usr/bin/mc mb localminio/setupshowroom &&
      /usr/bin/mc anonymous set download localminio/setupshowroom
      "
    networks:
      - setupshowroom

networks:
  setupshowroom:
    name: setupshowroom
    driver: bridge

volumes:
  minio_data: