apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: grafana-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <YOUR_EMAIL>
    privateKeySecretRef:
      name: grafana-letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
            serviceType: ClusterIP
